# The Occupancy {#occu}

Obtaining data for studies of animal populations is costly and wasteful, and it is not always possible to measure population density or demographic parameters such as birth or mortality rates. That is why the estimation of habitat occupation ($\psi$) is a good study tool since it is a reflection of other important population parameters such as abundance and density, which require a high number of records, with the economic and logistical costs involved. Additionally, and because detectability (_p_) in wild animals is not complete, the use of raw data generates underestimates of habitat occupation. Using repeated sampling, it is possible to generate estimates of detectability and, with this estimate, obtain unbiased values of habitat occupancy. Occupancy analysis methods were initially developed by [@MacKenzie2002] and later expanded by other authors [@MACKENZIE2005; @MacKenzie2006; @Kery2008; @Royle2007a; @Royle2005; @Royle2006]. These types of models allow inferences to be made about the effects of continuous and categorical variables on habitat occupancy. Furthermore, if sampling is done over long periods, it is also possible to estimate extinction and recolonization rates, which are useful in metapopulation studies [@MacKenzie2003]. This is a field of great development in biostatistics that has produced a great explosion of studies that use occupation taking detectability into account [@Guillera-Arroita2010a; @Guillera-Arroita2015; @Guillera-Arroita2011; @Guillera-Arroita2012; @Guillera-Arroita2014a; @Kery2013].
